<?php
/**
 * Created by PhpStorm.
 * User: darxan
 * Date: 2016/9/29
 * Time: 9:41
 */
define('PAGE_SIZE',10);
define('KEY_REQUEST_METHOD',0);
define('KEY_ROUTER',1);
define('KEY_AUTH',2);



define('CURRENT_LOGIN_VERIFIED','CURRENT_LOGIN_VERIFIED');
define('CURRENT_LOGIN_NAME','CURRENT_LOGIN_NAME');
define('CURRENT_LOGIN_PHONE','CURRENT_LOGIN_PHONE');
define('CURRENT_LOGIN_AVATAR','CURRENT_LOGIN_AVATAR');
define('CURRENT_LOGIN_ID','CURRENT_LOGIN_ID');
define('CURRENT_LOGIN_PRAISE_RATE_BUYER','CURRENT_LOGIN_PRAISE_RATE_BUYER');
define('CURRENT_LOGIN_PRAISE_RATE_SELLER','CURRENT_LOGIN_PRAISE_RATE_SELLER');

define('ACCESS_COUNT','ACCESS_COUNT');
define('ACCESS_LAST_TIME','ACCESS_LAST_TIME');
define('ACCESS_TIME_INTERVAL',0);
define('ACCESS_FREQUENCY_LIMIT',100);


define('TRANSACTION_STARTED',0);
define('TRANSACTION_CONFIRM',1);
define('TRANSACTION_REFUSED',2);


define('DEFAULT_AVATAR','/avatar.jpg');
